# This is a basic workflow to help you get started with Actions

name: DemoNew

# Controls when the action will run. 
on:
  workflow_dispatch:

 
jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - name: Run a one-line script
         run: echo Hello, world!
         
  deploy-dev:
     runs-on: ubuntu-latest
     environment: 
       name: dev
       url: 'teste.com'
     needs: build
     steps:
       - name: Run a one-line scr
         run: echo Deploy Dev!
  deploy-hmg:
     runs-on: ubuntu-latest
     environment: 
       name: hmg
       url: 'teste.com'
     needs: deploy-dev
     steps:
       - name: Run a one-line scr
         run: echo Deploy Hmg!
  deploy-prod:
     runs-on: ubuntu-latest
     environment: 
       name: prod
       url: 'teste.com'
     needs: deploy-hmg
     steps:
       - name: Run a one-line scr
         run: echo Deploy prod!
